keycloak:
  enabled: true
  realm: kakao
  auth-server-url: http://localhost:8080
  #기본값은 외부 요청에 HTTPS가 기본적으로 필요하다는 외부 의미 유효한 값은 'all', 'external', 'none'
  ssl-required: external
  resource: daum
  credentials:
    secret: BUXPklutbeYYoioHwPd1HjNHQqHDpIre
  use-resource-role-mappings: true
  bearer-only: true

server:
  port: 8081